### ISSUE TITLE
Could you share the dataset?

### ISSUE THREAD

**Issue by wkzza1830** [tubutubucorn/Improved_MalGAN#1]
Hi, @tubutubucorn 
Thank you for providing the implementation code of the Improved-MalGAN model. 
According to your paper, FFRI 2018 Dataset is used in this project. However, I didn't find this dataset in the references. 
<img width="493" alt="References" src="https://user-images.githubusercontent.com/59675268/82002850-84c2ba80-9691-11ea-9578-585eb5aef156.PNG">
I could't find "Datasets for Anti-Malware Research MWS Datasets 2018" in Google Scholar, and there're only some news reports about the MWS competition in https://www.iwsec.org/mws/2018/.

So, could you share the FFRI 2018 dataset? It will only be used for academic research.

**Comment by tubutubucorn** [comment]
Hi, @wkzza1830 
Thank you for your inquiry.

The FFRI 2018 dataset is only shared under contract with the MWS Executive Committee, the contract prohibits the sharing of the dataset to third parties. Also, the contract is contingent upon your contributions to the MWS community (e.g., submission of papers, participation in competitions).

If you would like to use the dataset, please contact at the following email address.
MWS 2019 Executive Committee Secretariat (mws2019-inquiry [at] ml.labs.fujitsu.com)

**Comment by wkzza1830** [comment]
Thank you for your reply.^_^
